version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 30
      runas: root
    - location: scripts/start_server
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 30
      runas: root

